name: iaxel
description: Sample project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.4
  logger: ^1.0.0
  http: ^0.13.1
  intl: ^0.17.0
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  enum_to_string: ^2.0.1
  freezed_annotation: ^1.1.0
  cached_network_image: ^3.1.0
  easy_localization: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_cached_pdfview: ^0.4.1
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.1
  freezed: ^1.1.1
  flutter_launcher_icons: ^0.9.2
  mocktail: ^0.3.0-dev.1

dependency_overrides:
  test_api: 0.4.9

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300